# coding: utf-8
"""Waylay rules engine models.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.batch_task_command import BatchTaskCommand
from ..models.batch_update_plugin import BatchUpdatePlugin
from ..models.batch_update_properties import BatchUpdateProperties

ATasksBatchOperationSpecification = Union[
    Annotated[BatchUpdatePlugin, ""],
    Annotated[BatchTaskCommand, ""],
    Annotated[BatchUpdateProperties, ""],
]
"""ATasksBatchOperationSpecification."""
