# coding: utf-8
"""Waylay rules engine models.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    Field,
    StrictInt,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.batch_operation import BatchOperation


class BatchOperationEnqueued(WaylayBaseModel):
    """BatchOperationEnqueued."""

    status_code: StrictInt = Field(alias="statusCode")
    uri: StrictStr = Field(
        description="URI where the batch operation status can be followed"
    )
    entity: BatchOperation

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
