# coding: utf-8
"""Waylay rules engine models.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    Field,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.batch_task_entity import BatchTaskEntity
from ..models.batch_task_query import BatchTaskQuery
from ..models.plugin_update_spec import PluginUpdateSpec
from ..models.template_modification_operation import TemplateModificationOperation


class BatchUpdatePlugin(WaylayBaseModel):
    """Upgrade plugins on multiple tasks."""

    entity: BatchTaskEntity
    action: TemplateModificationOperation
    query: BatchTaskQuery
    action_parameters: PluginUpdateSpec = Field(alias="actionParameters")

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="allow"
    )
