# coding: utf-8
"""Waylay rules engine models.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.batch_task_entity import BatchTaskEntity
from ..models.batch_task_query import BatchTaskQuery


class BatchTask(WaylayBaseModel):
    """BatchTask."""

    entity: BatchTaskEntity | None = None
    action: StrictStr | None = None
    query: BatchTaskQuery | None = None

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
