# coding: utf-8
"""Waylay rules engine models.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import List

from pydantic import (
    ConfigDict,
    Field,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.validation_issue import ValidationIssue


class CreateTask201Response(WaylayBaseModel):
    """CreateTask201Response."""

    id: StrictStr = Field(description="Unique task identifier", alias="ID")
    warnings: List[ValidationIssue] | None = Field(
        default=None,
        description="List of task warning issues. Will only be there if query parameter `returnWarnings` was set to `true`",
    )

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
