# coding: utf-8
"""Waylay rules engine models.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import Any, Dict

from pydantic import (
    ConfigDict,
    Field,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel


class ExecutePlugsSpecification(WaylayBaseModel):
    """ExecutePlugsSpecification."""

    properties: Dict[str, Any] | None = None
    resource: StrictStr | None = Field(
        default=None, description="Unique resource identifier"
    )
    stream_data: Dict[str, Any] | None = Field(default=None, alias="streamData")

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
