# coding: utf-8
"""Waylay rules engine models.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import Any, Dict

from pydantic import (
    ConfigDict,
    Field,
    StrictBool,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel


class GenericTaskSettings(WaylayBaseModel):
    """GenericTaskSettings."""

    name: StrictStr | None = None
    resource: StrictStr | None = Field(
        default=None, description="Unique resource identifier"
    )
    reset_observations: StrictBool | None = Field(
        default=True, alias="resetObservations"
    )
    parallel: StrictBool | None = True
    gates_need_full_observation: StrictBool | None = Field(
        default=False, alias="gatesNeedFullObservation"
    )
    tags: Dict[str, Any] | None = Field(
        default=None,
        description="Key-value pairs on which you can set at task creation and later filter tasks",
    )
    variables: Dict[str, Any] | None = Field(
        default=None,
        description="set of variables which will be used when starting a task and will automatically be injected in the template before starting a task.",
    )

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
