# coding: utf-8
"""Waylay rules engine models.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    Field,
    StrictStr,
)
from typing_extensions import (
    Annotated,  # >=3.11
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel


class GenericTrigger(WaylayBaseModel):
    """GenericTrigger."""

    source_label: StrictStr | None = Field(
        default=None, description="Unique node label", alias="sourceLabel"
    )
    destination_label: StrictStr | None = Field(
        default=None, description="Unique node label", alias="destinationLabel"
    )
    invocation_policy: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=None, alias="invocationPolicy"
    )

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
