# coding: utf-8
"""Waylay rules engine models.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import Any, Dict

from pydantic import (
    ConfigDict,
    Field,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel


class PatchTaskNodeRequest(WaylayBaseModel):
    """PatchTaskNodeRequest."""

    state: StrictStr | None = Field(
        default=None,
        description="State to set. Should be one of the supported states of the sensor",
    )
    raw_data: Dict[str, Any] | None = Field(
        default=None, description="rawData to set", alias="rawData"
    )

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="ignore",
    )
