# coding: utf-8
"""Waylay rules engine models.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import Any, Dict

from pydantic import (
    ConfigDict,
    Field,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel


class PropertyUpdatesSpec(WaylayBaseModel):
    """PropertyUpdatesSpec."""

    variables: Dict[str, Any] | None = Field(
        default=None,
        description="Set of variables to update. Will be merged with the current variables. To delete any of the current variables (and fall back to the default value from the template) set the value to `null`",
    )
    tags: Dict[str, Any] | None = Field(
        default=None,
        description="Key-value pairs. Will be merged with the current tags. To delete any of the current tags set the value to `null`",
    )

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
