# coding: utf-8
"""Waylay rules engine models.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.execution_trigger import ExecutionTrigger
from ..models.state_change_trigger import StateChangeTrigger
from ..models.states_trigger import StatesTrigger

SimplifiedGraphTriggersInner = Union[
    Annotated[StateChangeTrigger, ""],
    Annotated[StatesTrigger, ""],
    Annotated[ExecutionTrigger, ""],
]
"""SimplifiedGraphTriggersInner."""
