# coding: utf-8
"""Waylay rules engine models.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import List

from pydantic import (
    ConfigDict,
    Field,
    StrictBool,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.plugin_update_spec import PluginUpdateSpec
from ..models.template_modification_operation import TemplateModificationOperation


class TemplateModification(WaylayBaseModel):
    """TemplateModification."""

    operation: TemplateModificationOperation
    updates: List[PluginUpdateSpec]
    reload_tasks: StrictBool | None = Field(
        default=False,
        description="Should all tasks created from the template be reloaded",
        alias="reloadTasks",
    )

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
