# coding: utf-8
"""Waylay rules engine models.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from enum import Enum


class ValidationIssueSeverity(str, Enum):
    """Severity of the issue. ERROR means that object cannot be created if the issue is not fixed. WARNING means that the object can be created, but that errors might be encountered at runtime."""

    ERROR = "ERROR"
    WARNING = "WARNING"

    def __str__(self) -> str:
        return str(self.value)
