# coding: utf-8
"""Waylay rules engine api tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
import re
from importlib.util import find_spec
from typing import Union
from urllib.parse import quote

import pytest
from pytest_httpx import HTTPXMock
from typeguard import check_type
from waylay.sdk import ApiClient, WaylayClient
from waylay.sdk.api._models import Model
from waylay.services.rules.api import TasksBatchOperationsApi
from waylay.services.rules.service import RulesService

from ..types.batch_operation_enqueued_stub import BatchOperationEnqueuedStub
from ..types.get_batch_operation200_response_stub import (
    GetBatchOperation200ResponseStub,
)

MODELS_AVAILABLE = (
    True if find_spec("waylay.services.rules.models") is not None else False
)

if MODELS_AVAILABLE:
    from waylay.services.rules.models import (
        BatchOperationEnqueued,
        GetBatchOperation200Response,
    )


# some mappings that are needed for some <example> interpolations
null, true, false = None, True, False


@pytest.fixture
def tasks_batch_operations_api(waylay_api_client: ApiClient) -> TasksBatchOperationsApi:
    return TasksBatchOperationsApi(waylay_api_client)


def test_registered(waylay_client: WaylayClient):
    """Test that TasksBatchOperationsApi api is registered in the sdk client."""
    assert isinstance(
        waylay_client.rules.tasks_batch_operations, TasksBatchOperationsApi
    )


def _get_set_mock_response(httpx_mock: HTTPXMock, gateway_url: str, batchId: str):
    mock_response = GetBatchOperation200ResponseStub.create_json()
    httpx_mock_kwargs = {
        "method": "GET",
        "url": re.compile(f"^{gateway_url}/rules/v1/batch/{batchId}(\\?.*)?"),
        "content": json.dumps(mock_response, default=str),
        "status_code": 200,
    }
    httpx_mock.add_response(**httpx_mock_kwargs)


@pytest.mark.asyncio
@pytest.mark.skipif(not MODELS_AVAILABLE, reason="Types not installed.")
async def test_get(service: RulesService, gateway_url: str, httpx_mock: HTTPXMock):
    """Test case for get
    Get Tasks Batch Operation Status
    """
    # set path params
    batchId = "batch_id_example"

    kwargs = {}
    _get_set_mock_response(httpx_mock, gateway_url, quote(str(batchId)))
    resp = await service.tasks_batch_operations.get(batchId, **kwargs)
    check_type(resp, Union[GetBatchOperation200Response,])


@pytest.mark.asyncio
@pytest.mark.skipif(MODELS_AVAILABLE, reason="Types installed.")
async def test_get_without_types(
    service: RulesService, gateway_url: str, httpx_mock: HTTPXMock
):
    """Test case for get with models not installed
    Get Tasks Batch Operation Status
    """
    # set path params
    batchId = "batch_id_example"

    kwargs = {}
    _get_set_mock_response(httpx_mock, gateway_url, quote(str(batchId)))
    resp = await service.tasks_batch_operations.get(batchId, **kwargs)
    check_type(resp, Model)


def _start_set_mock_response(httpx_mock: HTTPXMock, gateway_url: str):
    mock_response = BatchOperationEnqueuedStub.create_json()
    httpx_mock_kwargs = {
        "method": "POST",
        "url": re.compile(f"^{gateway_url}/rules/v1/batch(\\?.*)?"),
        "content": json.dumps(mock_response, default=str),
        "status_code": 202,
    }
    httpx_mock.add_response(**httpx_mock_kwargs)


@pytest.mark.asyncio
@pytest.mark.skipif(not MODELS_AVAILABLE, reason="Types not installed.")
async def test_start(service: RulesService, gateway_url: str, httpx_mock: HTTPXMock):
    """Test case for start
    Start Batch Operations
    """
    # set path params
    kwargs = {}
    _start_set_mock_response(httpx_mock, gateway_url)
    resp = await service.tasks_batch_operations.start(**kwargs)
    check_type(resp, Union[BatchOperationEnqueued,])


@pytest.mark.asyncio
@pytest.mark.skipif(MODELS_AVAILABLE, reason="Types installed.")
async def test_start_without_types(
    service: RulesService, gateway_url: str, httpx_mock: HTTPXMock
):
    """Test case for start with models not installed
    Start Batch Operations
    """
    # set path params
    kwargs = {}
    _start_set_mock_response(httpx_mock, gateway_url)
    resp = await service.tasks_batch_operations.start(**kwargs)
    check_type(resp, Model)
