# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.a_tasks_batch_operation_specification import (
        ATasksBatchOperationSpecification,
    )

    ATasksBatchOperationSpecificationAdapter = TypeAdapter(
        ATasksBatchOperationSpecification
    )
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

a_tasks_batch_operation_specification_model_schema = json.loads(
    r"""{
  "title" : "a tasks batch operation specification",
  "type" : "object",
  "oneOf" : [ {
    "$ref" : "#/components/schemas/BatchUpdatePlugin"
  }, {
    "$ref" : "#/components/schemas/BatchTaskCommand"
  }, {
    "$ref" : "#/components/schemas/BatchUpdateProperties"
  } ]
}
""",
    object_hook=with_example_provider,
)
a_tasks_batch_operation_specification_model_schema.update({
    "definitions": MODEL_DEFINITIONS
})

a_tasks_batch_operation_specification_faker = JSF(
    a_tasks_batch_operation_specification_model_schema, allow_none_optionals=1
)


class ATasksBatchOperationSpecificationStub:
    """ATasksBatchOperationSpecification unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return a_tasks_batch_operation_specification_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "ATasksBatchOperationSpecification":
        """Create ATasksBatchOperationSpecification stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                ATasksBatchOperationSpecificationAdapter.json_schema(),
                allow_none_optionals=1,
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return ATasksBatchOperationSpecificationAdapter.validate_python(
            json, context={"skip_validation": True}
        )
