# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.batch_update_properties import (
        BatchUpdateProperties,
    )

    BatchUpdatePropertiesAdapter = TypeAdapter(BatchUpdateProperties)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

batch_update_properties_model_schema = json.loads(
    r"""{
  "title" : "BatchUpdateProperties",
  "type" : "object",
  "description" : "Update variables and/or tags of multiple tasks",
  "allOf" : [ {
    "$ref" : "#/components/schemas/BatchTask"
  }, {
    "required" : [ "action", "actionParameters", "entity", "query" ],
    "properties" : {
      "action" : {
        "$ref" : "#/components/schemas/BatchUpdateProperties_allOf_action"
      },
      "actionParameters" : {
        "$ref" : "#/components/schemas/PropertyUpdatesSpec"
      }
    }
  } ]
}
""",
    object_hook=with_example_provider,
)
batch_update_properties_model_schema.update({"definitions": MODEL_DEFINITIONS})

batch_update_properties_faker = JSF(
    batch_update_properties_model_schema, allow_none_optionals=1
)


class BatchUpdatePropertiesStub:
    """BatchUpdateProperties unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return batch_update_properties_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "BatchUpdateProperties":
        """Create BatchUpdateProperties stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                BatchUpdatePropertiesAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return BatchUpdatePropertiesAdapter.validate_python(
            json, context={"skip_validation": True}
        )
