# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.batch_task_command_all_of_action import (
        BatchTaskCommandAllOfAction,
    )

    BatchTaskCommandAllOfActionAdapter = TypeAdapter(BatchTaskCommandAllOfAction)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

batch_task_command_all_of_action_model_schema = json.loads(
    r"""{
  "title" : "BatchTaskCommand_allOf_action",
  "type" : "string",
  "enum" : [ "delete", "start", "restart", "stop", "reload", "stopAndDelete" ]
}
""",
    object_hook=with_example_provider,
)
batch_task_command_all_of_action_model_schema.update({"definitions": MODEL_DEFINITIONS})

batch_task_command_all_of_action_faker = JSF(
    batch_task_command_all_of_action_model_schema, allow_none_optionals=1
)


class BatchTaskCommandAllOfActionStub:
    """BatchTaskCommandAllOfAction unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return batch_task_command_all_of_action_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "BatchTaskCommandAllOfAction":
        """Create BatchTaskCommandAllOfAction stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                BatchTaskCommandAllOfActionAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return BatchTaskCommandAllOfActionAdapter.validate_python(
            json, context={"skip_validation": True}
        )
