# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.batch_task import BatchTask

    BatchTaskAdapter = TypeAdapter(BatchTask)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

batch_task_model_schema = json.loads(
    r"""{
  "type" : "object",
  "properties" : {
    "entity" : {
      "$ref" : "#/components/schemas/BatchTask_entity"
    },
    "action" : {
      "type" : "string"
    },
    "query" : {
      "$ref" : "#/components/schemas/BatchTask_query"
    }
  }
}
""",
    object_hook=with_example_provider,
)
batch_task_model_schema.update({"definitions": MODEL_DEFINITIONS})

batch_task_faker = JSF(batch_task_model_schema, allow_none_optionals=1)


class BatchTaskStub:
    """BatchTask unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return batch_task_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "BatchTask":
        """Create BatchTask stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(BatchTaskAdapter.json_schema(), allow_none_optionals=1)
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return BatchTaskAdapter.validate_python(json, context={"skip_validation": True})
