# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.batch_id_query import BatchIdQuery

    BatchIdQueryAdapter = TypeAdapter(BatchIdQuery)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

batch_id_query_model_schema = json.loads(
    r"""{
  "required" : [ "ids" ],
  "type" : "object",
  "properties" : {
    "ids" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/TaskId"
      }
    }
  }
}
""",
    object_hook=with_example_provider,
)
batch_id_query_model_schema.update({"definitions": MODEL_DEFINITIONS})

batch_id_query_faker = JSF(batch_id_query_model_schema, allow_none_optionals=1)


class BatchIdQueryStub:
    """BatchIdQuery unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return batch_id_query_faker.generate()

    @classmethod
    def create_instance(cls) -> "BatchIdQuery":
        """Create BatchIdQuery stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return BatchIdQueryAdapter.validate_python(cls.create_json())
