# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.create_task201_response import (
        CreateTask201Response,
    )

    CreateTask201ResponseAdapter = TypeAdapter(CreateTask201Response)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

create_task_201_response_model_schema = json.loads(
    r"""{
  "required" : [ "ID" ],
  "type" : "object",
  "properties" : {
    "ID" : {
      "$ref" : "#/components/schemas/TaskId"
    },
    "warnings" : {
      "type" : "array",
      "description" : "List of task warning issues. Will only be there if query parameter `returnWarnings` was set to `true`",
      "items" : {
        "$ref" : "#/components/schemas/ValidationIssue"
      }
    }
  }
}
""",
    object_hook=with_example_provider,
)
create_task_201_response_model_schema.update({"definitions": MODEL_DEFINITIONS})

create_task_201_response_faker = JSF(
    create_task_201_response_model_schema, allow_none_optionals=1
)


class CreateTask201ResponseStub:
    """CreateTask201Response unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return create_task_201_response_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "CreateTask201Response":
        """Create CreateTask201Response stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                CreateTask201ResponseAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return CreateTask201ResponseAdapter.validate_python(
            json, context={"skip_validation": True}
        )
