# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.error_with_details_response import (
        ErrorWithDetailsResponse,
    )

    ErrorWithDetailsResponseAdapter = TypeAdapter(ErrorWithDetailsResponse)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

error_with_details_response_model_schema = json.loads(
    r"""{
  "allOf" : [ {
    "$ref" : "#/components/schemas/ErrorResponse"
  }, {
    "properties" : {
      "details" : {
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/ValidationIssue"
        }
      }
    }
  } ]
}
""",
    object_hook=with_example_provider,
)
error_with_details_response_model_schema.update({"definitions": MODEL_DEFINITIONS})

error_with_details_response_faker = JSF(
    error_with_details_response_model_schema, allow_none_optionals=1
)


class ErrorWithDetailsResponseStub:
    """ErrorWithDetailsResponse unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return error_with_details_response_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "ErrorWithDetailsResponse":
        """Create ErrorWithDetailsResponse stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                ErrorWithDetailsResponseAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return ErrorWithDetailsResponseAdapter.validate_python(
            json, context={"skip_validation": True}
        )
