# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.get_template200_response import (
        GetTemplate200Response,
    )

    GetTemplate200ResponseAdapter = TypeAdapter(GetTemplate200Response)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

get_template_200_response_model_schema = json.loads(
    r"""{
  "allOf" : [ {
    "$ref" : "#/components/schemas/TemplateEntityMetadata"
  }, {
    "$ref" : "#/components/schemas/GraphDefinition"
  } ]
}
""",
    object_hook=with_example_provider,
)
get_template_200_response_model_schema.update({"definitions": MODEL_DEFINITIONS})

get_template_200_response_faker = JSF(
    get_template_200_response_model_schema, allow_none_optionals=1
)


class GetTemplate200ResponseStub:
    """GetTemplate200Response unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return get_template_200_response_faker.generate()

    @classmethod
    def create_instance(cls) -> "GetTemplate200Response":
        """Create GetTemplate200Response stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return GetTemplate200ResponseAdapter.validate_python(cls.create_json())
