# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.list_tasks200_response import ListTasks200Response

    ListTasks200ResponseAdapter = TypeAdapter(ListTasks200Response)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

list_tasks_200_response_model_schema = json.loads(
    r"""{
  "type" : "object",
  "allOf" : [ {
    "properties" : {
      "values" : {
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/TaskEntity"
        }
      }
    }
  }, {
    "$ref" : "#/components/schemas/PagingResult"
  } ]
}
""",
    object_hook=with_example_provider,
)
list_tasks_200_response_model_schema.update({"definitions": MODEL_DEFINITIONS})

list_tasks_200_response_faker = JSF(
    list_tasks_200_response_model_schema, allow_none_optionals=1
)


class ListTasks200ResponseStub:
    """ListTasks200Response unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return list_tasks_200_response_faker.generate()

    @classmethod
    def create_instance(cls) -> "ListTasks200Response":
        """Create ListTasks200Response stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return ListTasks200ResponseAdapter.validate_python(cls.create_json())
