# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.logs_inner_level import LogsInnerLevel

    LogsInnerLevelAdapter = TypeAdapter(LogsInnerLevel)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

logs_inner_level_model_schema = json.loads(
    r"""{
  "title" : "Logs_inner_level",
  "type" : "string",
  "example" : "INFO",
  "enum" : [ "DEBUG", "INFO", "WARN", "ERROR" ]
}
""",
    object_hook=with_example_provider,
)
logs_inner_level_model_schema.update({"definitions": MODEL_DEFINITIONS})

logs_inner_level_faker = JSF(logs_inner_level_model_schema, allow_none_optionals=1)


class LogsInnerLevelStub:
    """LogsInnerLevel unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return logs_inner_level_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "LogsInnerLevel":
        """Create LogsInnerLevel stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                LogsInnerLevelAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return LogsInnerLevelAdapter.validate_python(
            json, context={"skip_validation": True}
        )
