# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.periodic_task_setting import PeriodicTaskSetting

    PeriodicTaskSettingAdapter = TypeAdapter(PeriodicTaskSetting)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

periodic_task_setting_model_schema = json.loads(
    r"""{
  "required" : [ "type" ],
  "type" : "object",
  "properties" : {
    "type" : {
      "$ref" : "#/components/schemas/PeriodicTaskSetting_type"
    },
    "frequency" : {
      "type" : "integer",
      "description" : "polling frequency in milliseconds",
      "example" : 900000
    }
  }
}
""",
    object_hook=with_example_provider,
)
periodic_task_setting_model_schema.update({"definitions": MODEL_DEFINITIONS})

periodic_task_setting_faker = JSF(
    periodic_task_setting_model_schema, allow_none_optionals=1
)


class PeriodicTaskSettingStub:
    """PeriodicTaskSetting unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return periodic_task_setting_faker.generate()

    @classmethod
    def create_instance(cls) -> "PeriodicTaskSetting":
        """Create PeriodicTaskSetting stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return PeriodicTaskSettingAdapter.validate_python(cls.create_json())
