# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.plugin_update_spec_from_version import (
        PluginUpdateSpecFromVersion,
    )

    PluginUpdateSpecFromVersionAdapter = TypeAdapter(PluginUpdateSpecFromVersion)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

plugin_update_spec_from_version_model_schema = json.loads(
    r"""{
  "title" : "PluginUpdateSpec_fromVersion",
  "description" : "plugin version selection to upgrade",
  "example" : "any",
  "oneOf" : [ {
    "$ref" : "#/components/schemas/Version"
  }, {
    "$ref" : "#/components/schemas/PluginUpdateSpec_fromVersion_oneOf"
  } ]
}
""",
    object_hook=with_example_provider,
)
plugin_update_spec_from_version_model_schema.update({"definitions": MODEL_DEFINITIONS})

plugin_update_spec_from_version_faker = JSF(
    plugin_update_spec_from_version_model_schema, allow_none_optionals=1
)


class PluginUpdateSpecFromVersionStub:
    """PluginUpdateSpecFromVersion unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return plugin_update_spec_from_version_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "PluginUpdateSpecFromVersion":
        """Create PluginUpdateSpecFromVersion stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                PluginUpdateSpecFromVersionAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return PluginUpdateSpecFromVersionAdapter.validate_python(
            json, context={"skip_validation": True}
        )
