# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.possible_values_enum_declaration_inner import (
        PossibleValuesEnumDeclarationInner,
    )

    PossibleValuesEnumDeclarationInnerAdapter = TypeAdapter(
        PossibleValuesEnumDeclarationInner
    )
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

possible_values__enum_declaration__inner_model_schema = json.loads(
    r"""{
  "title" : "Possible_values__enum_declaration__inner",
  "oneOf" : [ {
    "type" : "string"
  }, {
    "type" : "number"
  }, {
    "type" : "object"
  } ]
}
""",
    object_hook=with_example_provider,
)
possible_values__enum_declaration__inner_model_schema.update({
    "definitions": MODEL_DEFINITIONS
})

possible_values__enum_declaration__inner_faker = JSF(
    possible_values__enum_declaration__inner_model_schema, allow_none_optionals=1
)


class PossibleValuesEnumDeclarationInnerStub:
    """PossibleValuesEnumDeclarationInner unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return possible_values__enum_declaration__inner_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "PossibleValuesEnumDeclarationInner":
        """Create PossibleValuesEnumDeclarationInner stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                PossibleValuesEnumDeclarationInnerAdapter.json_schema(),
                allow_none_optionals=1,
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return PossibleValuesEnumDeclarationInnerAdapter.validate_python(
            json, context={"skip_validation": True}
        )
