# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.replace_template200_response import (
        ReplaceTemplate200Response,
    )

    ReplaceTemplate200ResponseAdapter = TypeAdapter(ReplaceTemplate200Response)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

replace_template_200_response_model_schema = json.loads(
    r"""{
  "allOf" : [ {
    "$ref" : "#/components/schemas/TemplateEntityMetadata"
  }, {
    "$ref" : "#/components/schemas/SimplifiedGraph"
  } ]
}
""",
    object_hook=with_example_provider,
)
replace_template_200_response_model_schema.update({"definitions": MODEL_DEFINITIONS})

replace_template_200_response_faker = JSF(
    replace_template_200_response_model_schema, allow_none_optionals=1
)


class ReplaceTemplate200ResponseStub:
    """ReplaceTemplate200Response unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return replace_template_200_response_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "ReplaceTemplate200Response":
        """Create ReplaceTemplate200Response stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                ReplaceTemplate200ResponseAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return ReplaceTemplate200ResponseAdapter.validate_python(
            json, context={"skip_validation": True}
        )
