# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.resource_data_injection import (
        ResourceDataInjection,
    )

    ResourceDataInjectionAdapter = TypeAdapter(ResourceDataInjection)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

resource_data_injection_model_schema = json.loads(
    r"""{
  "title" : "ResourceDataInjection",
  "required" : [ "resource" ],
  "type" : "object",
  "properties" : {
    "resource" : {
      "$ref" : "#/components/schemas/ResourceId"
    },
    "timestamp" : {
      "$ref" : "#/components/schemas/UnixEpochMillis"
    }
  },
  "additionalProperties" : true,
  "description" : "data to inject per resource"
}
""",
    object_hook=with_example_provider,
)
resource_data_injection_model_schema.update({"definitions": MODEL_DEFINITIONS})

resource_data_injection_faker = JSF(
    resource_data_injection_model_schema, allow_none_optionals=1
)


class ResourceDataInjectionStub:
    """ResourceDataInjection unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return resource_data_injection_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "ResourceDataInjection":
        """Create ResourceDataInjection stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                ResourceDataInjectionAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return ResourceDataInjectionAdapter.validate_python(
            json, context={"skip_validation": True}
        )
