# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.run_template_log_level_parameter import (
        RunTemplateLogLevelParameter,
    )

    RunTemplateLogLevelParameterAdapter = TypeAdapter(RunTemplateLogLevelParameter)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

run_template_log_level_parameter_model_schema = json.loads(
    r"""{
  "type" : "string",
  "default" : "DEBUG",
  "enum" : [ "DEBUG", "INFO", "WARN", "ERROR" ]
}
""",
    object_hook=with_example_provider,
)
run_template_log_level_parameter_model_schema.update({"definitions": MODEL_DEFINITIONS})

run_template_log_level_parameter_faker = JSF(
    run_template_log_level_parameter_model_schema, allow_none_optionals=1
)


class RunTemplateLogLevelParameterStub:
    """RunTemplateLogLevelParameter unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return run_template_log_level_parameter_faker.generate()

    @classmethod
    def create_instance(cls) -> "RunTemplateLogLevelParameter":
        """Create RunTemplateLogLevelParameter stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return RunTemplateLogLevelParameterAdapter.validate_python(cls.create_json())
