# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.scheduled_task_setting_all_of_type import (
        ScheduledTaskSettingAllOfType,
    )

    ScheduledTaskSettingAllOfTypeAdapter = TypeAdapter(ScheduledTaskSettingAllOfType)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

scheduled_task_setting_all_of_type_model_schema = json.loads(
    r"""{
  "title" : "ScheduledTaskSetting_allOf_type",
  "type" : "string",
  "enum" : [ "scheduled" ]
}
""",
    object_hook=with_example_provider,
)
scheduled_task_setting_all_of_type_model_schema.update({
    "definitions": MODEL_DEFINITIONS
})

scheduled_task_setting_all_of_type_faker = JSF(
    scheduled_task_setting_all_of_type_model_schema, allow_none_optionals=1
)


class ScheduledTaskSettingAllOfTypeStub:
    """ScheduledTaskSettingAllOfType unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return scheduled_task_setting_all_of_type_faker.generate()

    @classmethod
    def create_instance(cls) -> "ScheduledTaskSettingAllOfType":
        """Create ScheduledTaskSettingAllOfType stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return ScheduledTaskSettingAllOfTypeAdapter.validate_python(cls.create_json())
