# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.scheduled_task_setting import ScheduledTaskSetting

    ScheduledTaskSettingAdapter = TypeAdapter(ScheduledTaskSetting)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

scheduled_task_setting_model_schema = json.loads(
    r"""{
  "type" : "object",
  "allOf" : [ {
    "required" : [ "type" ],
    "properties" : {
      "type" : {
        "$ref" : "#/components/schemas/ScheduledTaskSetting_allOf_type"
      },
      "timeZone" : {
        "$ref" : "#/components/schemas/TimeZoneId"
      }
    }
  }, {
    "nullable" : true,
    "oneOf" : [ ]
  } ]
}
""",
    object_hook=with_example_provider,
)
scheduled_task_setting_model_schema.update({"definitions": MODEL_DEFINITIONS})

scheduled_task_setting_faker = JSF(
    scheduled_task_setting_model_schema, allow_none_optionals=1
)


class ScheduledTaskSettingStub:
    """ScheduledTaskSetting unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return scheduled_task_setting_faker.generate()

    @classmethod
    def create_instance(cls) -> "ScheduledTaskSetting":
        """Create ScheduledTaskSetting stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return ScheduledTaskSettingAdapter.validate_python(cls.create_json())
