# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.stream_data import StreamData

    StreamDataAdapter = TypeAdapter(StreamData)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

stream_data_model_schema = json.loads(
    r"""{
  "title" : "stream data",
  "required" : [ "data", "resource" ],
  "type" : "object",
  "properties" : {
    "resource" : {
      "$ref" : "#/components/schemas/ResourceId"
    },
    "data" : {
      "$ref" : "#/components/schemas/stream_data_data"
    }
  }
}
""",
    object_hook=with_example_provider,
)
stream_data_model_schema.update({"definitions": MODEL_DEFINITIONS})

stream_data_faker = JSF(stream_data_model_schema, allow_none_optionals=1)


class StreamDataStub:
    """StreamData unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return stream_data_faker.generate()

    @classmethod
    def create_instance(cls) -> "StreamData":
        """Create StreamData stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return StreamDataAdapter.validate_python(cls.create_json())
