# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.task_with_rule_all_of_task import (
        TaskWithRuleAllOfTask,
    )

    TaskWithRuleAllOfTaskAdapter = TypeAdapter(TaskWithRuleAllOfTask)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

task_with_rule_all_of_task_model_schema = json.loads(
    r"""{
  "title" : "TaskWithRule_allOf_task",
  "allOf" : [ {
    "$ref" : "#/components/schemas/TaskSettings"
  }, {
    "required" : [ "name" ],
    "type" : "object",
    "properties" : {
      "start" : {
        "title" : "boolean to indicate whether task must be started after creation",
        "type" : "boolean",
        "default" : true
      }
    }
  } ]
}
""",
    object_hook=with_example_provider,
)
task_with_rule_all_of_task_model_schema.update({"definitions": MODEL_DEFINITIONS})

task_with_rule_all_of_task_faker = JSF(
    task_with_rule_all_of_task_model_schema, allow_none_optionals=1
)


class TaskWithRuleAllOfTaskStub:
    """TaskWithRuleAllOfTask unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return task_with_rule_all_of_task_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "TaskWithRuleAllOfTask":
        """Create TaskWithRuleAllOfTask stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                TaskWithRuleAllOfTaskAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return TaskWithRuleAllOfTaskAdapter.validate_python(
            json, context={"skip_validation": True}
        )
