# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.template_entity_common_attributes import (
        TemplateEntityCommonAttributes,
    )

    TemplateEntityCommonAttributesAdapter = TypeAdapter(TemplateEntityCommonAttributes)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

template_entity_common_attributes_model_schema = json.loads(
    r"""{
  "required" : [ "name" ],
  "type" : "object",
  "properties" : {
    "name" : {
      "$ref" : "#/components/schemas/TemplateId"
    },
    "discoveryTemplate" : {
      "type" : "boolean",
      "description" : "flag to indicate if the template is the discovery template",
      "example" : false
    },
    "tags" : {
      "$ref" : "#/components/schemas/TemplateTags"
    },
    "variables" : {
      "type" : "array",
      "description" : "Variable declarations",
      "items" : {
        "$ref" : "#/components/schemas/VariableDeclaration"
      }
    },
    "taskDefaults" : {
      "$ref" : "#/components/schemas/TaskDefaultsElement"
    },
    "description" : {
      "type" : "string",
      "description" : "Description of the template"
    },
    "notes" : {
      "type" : "array",
      "description" : "List of notes as explanation for users",
      "items" : {
        "$ref" : "#/components/schemas/NoteElement"
      }
    }
  }
}
""",
    object_hook=with_example_provider,
)
template_entity_common_attributes_model_schema.update({
    "definitions": MODEL_DEFINITIONS
})

template_entity_common_attributes_faker = JSF(
    template_entity_common_attributes_model_schema, allow_none_optionals=1
)


class TemplateEntityCommonAttributesStub:
    """TemplateEntityCommonAttributes unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return template_entity_common_attributes_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "TemplateEntityCommonAttributes":
        """Create TemplateEntityCommonAttributes stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                TemplateEntityCommonAttributesAdapter.json_schema(),
                allow_none_optionals=1,
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return TemplateEntityCommonAttributesAdapter.validate_python(
            json, context={"skip_validation": True}
        )
