# coding: utf-8
"""Waylay rules engine model tests.

This code was generated from the OpenAPI documentation of 'Waylay rules engine'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.rules.models.upgrade_plugins_templates200_response import (
        UpgradePluginsTemplates200Response,
    )

    UpgradePluginsTemplates200ResponseAdapter = TypeAdapter(
        UpgradePluginsTemplates200Response
    )
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

upgrade_plugins_templates_200_response_model_schema = json.loads(
    r"""{
  "type" : "object",
  "properties" : {
    "successful" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/TemplateId"
      }
    }
  }
}
""",
    object_hook=with_example_provider,
)
upgrade_plugins_templates_200_response_model_schema.update({
    "definitions": MODEL_DEFINITIONS
})

upgrade_plugins_templates_200_response_faker = JSF(
    upgrade_plugins_templates_200_response_model_schema, allow_none_optionals=1
)


class UpgradePluginsTemplates200ResponseStub:
    """UpgradePluginsTemplates200Response unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return upgrade_plugins_templates_200_response_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "UpgradePluginsTemplates200Response":
        """Create UpgradePluginsTemplates200Response stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                UpgradePluginsTemplates200ResponseAdapter.json_schema(),
                allow_none_optionals=1,
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return UpgradePluginsTemplates200ResponseAdapter.validate_python(
            json, context={"skip_validation": True}
        )
